AiJiaXi.Web/Areas/Admin/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Project.Common;
using Project.Common.Helpers;
using Project.Domain.Entities;
using Project.Domain.Entities.Orders;
using Project.Domain.Enums;
using Project.Domain.JsonModel;
using Project.Domain.Repositories.Interface;
using Project.Web.Filters;
using Microsoft.AspNet.Identity;
using Webdiyer.WebControls.Mvc;

namespace Project.Web.Areas.Admin.Controllers
{
    [AdminAuthorize]
    public class EventsController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;
        private IRepository<Agency> _agencyRepository;
        private IRepository<Event> _eventRepository;

        public EventsController(ApplicationUserManager userManager, ApplicationRoleManager roleManager,
            IRepository<Agency> agencyRepository, IRepository<Event> eventRepository)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _agencyRepository = agencyRepository;
            _eventRepository = eventRepository;
        }


        // GET: Admin/Event
        public async Task<ActionResult> Index(int id = 1)
        {
            var agencies = _agencyRepository.FindList<Agency>(item => item.IsValid).ToList();
            ViewBag.Agencies = new SelectList(agencies, "Id", "Name");
            var predicate = PredicateBuilder.True<Event>();

            var userId = User.Identity.GetUserId();
            var user = await this._userManager.FindByIdAsync(userId);
            if (user.UserType == UserType.Agency)
            {
                var agencyId = user.Agency.Id;
                predicate = predicate.And(item => item.Agencies.Select(m => m.Id).Contains(agencyId));
            }
            else if (user.UserType == UserType.User || user.UserType == UserType.Withdrawals)
            {
                throw new Exception("推广员和前台用户无权执行此操作！");
            }

            var model = this._eventRepository.FindList<Event>(predicate).OrderByDescending(a => a.EndTime).ToPagedList(id, 15);
            if (Request.IsAjaxRequest())
                return PartialView("_EventSearchResult", model);
            return View(model);
        }

        [HttpPost]
        public ActionResult EventsSearchPost(string eventType, string name, string startTime, string endTime, string status, int id = 1)
        {
            return EventsSearchResult(eventType,name, startTime, endTime, status, id);
        }

        private ActionResult EventsSearchResult(string eventType, string name, string startTime, string endTime, string status, int id = 1)
        {
            var predicate = PredicateBuilder.True<Event>();
            var userId = User.Identity.GetUserId();
            var user = this._userManager.FindById(userId);
            if (user.UserType == UserType.Agency)
            {
                var agencyId = user.Agency.Id;
                predicate = predicate.And(item => item.Agencies.Select(m => m.Id).Contains(agencyId));
            }
            else if (user.UserType == UserType.User || user.UserType == UserType.Withdrawals)
            {
                throw new Exception("推广员和前台用户无权执行此操作！");
            }

            if (!string.IsNullOrWhiteSpace(status))
            {
                switch (status)
                {
                    case "0":
                        predicate = predicate.And(item => item.StartTime > DateTime.Now);
                        break;
                    case "1":
                        predicate = predicate.And(item => item.StartTime <= DateTime.Now && item.EndTime > DateTime.Now);
                        break;
                    case "2":
                        predicate = predicate.And(item => item.EndTime <= DateTime.Now);
                        break;
                }
            }


            if (!string.IsNullOrWhiteSpace(name))
            {
                predicate = predicate.And(item => item.Name.Contains(name));
            }

            if (!string.IsNullOrWhiteSpace(startTime))
            {
                DateTime dt;
                bool flag = DateTime.TryParse(startTime, out dt);
                if (flag)
                {
                    predicate = predicate.And(item => item.StartTime >= dt);
                }
                else
                {
                    throw new Exception($"错误的时间格式({startTime})！");
                }
            }

            if (!string.IsNullOrWhiteSpace(endTime))
            {
                DateTime dt;
                bool flag = DateTime.TryParse(endTime, out dt);
                if (flag)
                {
                    predicate = predicate.And(item => item.StartTime <= dt);
                }
                else
                {
                    throw new Exception($"错误的时间格式({endTime})！");
                }
            }

            if (!string.IsNullOrWhiteSpace(eventType))
            {
                EventType etype;
                bool flag = Enum.TryParse(eventType, true, out etype);
                if (flag)
                {
                    predicate = predicate.And(item => item.EventType == etype);
                }
                else
                {
                    throw new Exception($"错误的活动类型({eventType})！");
                }
            }

            var model = this._eventRepository.FindList<OrderItemClass>(predicate).OrderBy(a => a.Id).ToPagedList(id, 15);
            if (Request.IsAjaxRequest())
                return PartialView("_EventSearchResult", model);
            return View(model);
        }

        public ActionResult Manage(long id = 0)
        {
            var userId = User.Identity.GetUserId();
            var user = this._userManager.FindById(userId);
            if (user.UserType != UserType.Admin)
            {
                throw new Exception("非管理员不能发布活动！");
            }

            ViewBag.Second = "发布活动";

            var agencies = _agencyRepository.FindList<Agency>(item => item.IsValid).ToList();
            ViewBag.Agencies = agencies;

            var entity = _eventRepository.Find(item => item.Id == id);
            if (entity == null)
            {
                return View(new Event() {StartTime = DateTime.Now, EndTime = DateTime.Now});
            }

            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Manage(FormCollection form, long id = 0)
        {
            var entity = _eventRepository.Find(item => item.Id == id);
            if (entity == null)
            {
                entity = new Event();
                if (this.TryUpdateModel(entity, null,form.AllKeys, new [] { "Desc" , "agencies" }))
                {
                    var agencies = form["agencies"].Split(',');
                    if (agencies.Any())
                    {
                        var list =
                            _agencyRepository.FindList<Agency>(item => agencies.Contains(item.Id.ToString())).ToList();

                        entity.Agencies = new List<Agency>();
                        entity.Agencies.AddRange(list);
                    }
                    entity.Desc = HttpUtility.HtmlEncode(form["Desc"]);
                    await _eventRepository.AddAsync(entity);
                }   
            }
            else
            {
                if (this.TryUpdateModel(entity, null, form.AllKeys, new[] { "Desc", "agencies" }))
                {
                    if (entity.Agencies == null)
                    {
                        entity.Agencies = new List<Agency>();
                    }
                    entity.Agencies.Clear();
                    var agencies = form["agencies"].Split(',');
                    if (agencies.Any())
                    {
                        entity.Agencies.AddRange(_agencyRepository.FindList<Agency>(item => agencies.Contains(item.Id.ToString())).ToList());
                    }
                    entity.Desc = HttpUtility.HtmlEncode(form["Desc"]);
                    await _eventRepository.UpdateAsync(entity);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(long id)
        {
            var userId = User.Identity.GetUserId();
            var user = this._userManager.FindById(userId);
            if (user.UserType != UserType.Admin)
            {
                throw new Exception("当前用户没有执行此操作的权限!");
            }

            var entity = _eventRepository.Find(item => item.Id == id);

            if (entity == null)
            {
                return JavaScript("layer.alert('该优惠券不存在，删除失败！');");
            }

            var result = await _eventRepository.DeleteAsync(entity);
            if (!result)
            {
                return JavaScript("layer.alert('删除过程中发生异常，删除失败！');");
            }

            var model =
                this._eventRepository.FindList<Event>(item => true)
                    .OrderBy(a => a.Id)
                    .ToPagedList(1, 15);

            return PartialView("_EventSearchResult", model);
        }

        public ActionResult ApplyStatus()
        {
            var select2Items = (from object value in Enum.GetValues(typeof (ApplyStatus))
                select new Select2Item() {value = value.ToString(), text = value.GetDescription()}).ToList();

            return Json(select2Items, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Flags()
        {
            var select2Items = new List<Select2Item>()
            {
                new Select2Item() {value = "true", text = "进行中"},
                new Select2Item() {value = "false", text = "尚未开启"}
            };

AiJiaXi.Web/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Project.Domain.Entities;
using Project.Domain.Entities.Orders;
using Project.Domain.Enums;
using Project.Domain.Repositories.Interface;
using Project.Domain.ViewModels.Admin;
using Project.Web.Filters;
using Microsoft.AspNet.Identity;

namespace Project.Web.Areas.Admin.Controllers
{
    [AdminAuthorize]
    public class HomeController : Controller
    {
        private ApplicationUserManager _userManager;
        private IRepository<JoinApplication> _joinApplicationRepository;
        private IRepository<Order> _orderRepository;

        public HomeController(ApplicationUserManager userManager, IRepository<JoinApplication> joinApplicationRepository,
            IRepository<Order> orderRepository)
        {
            _userManager = userManager;
            _joinApplicationRepository = joinApplicationRepository;
            _orderRepository = orderRepository;
        }

        // GET: Admin/Home
        public async Task<ActionResult> Index()
        {
            var userId = this.User.Identity.GetUserId();
            var user = await _userManager.FindByIdAsync(userId);

            switch (user.UserType)
            {
                case UserType.Admin:
                    ViewBag.Joins = _joinApplicationRepository.Count(item => item.FeedbackStatus == FeedbackStatus.UnDealed);
                    ViewBag.Users = _userManager.Users.Count(item => item.UserType == UserType.User);
                    ViewBag.Completes = _orderRepository.Count(item => item.OrderStatus == OrderStatus.Succeed);
                    ViewBag.Turnover =
                        _orderRepository.FindList<Order>(item => item.OrderStatus == OrderStatus.Succeed).ToList()
                            .Sum(item => item.Fact);

                    return View("Summary");
                case UserType.Agency:
                    ViewBag.Going =
                        _orderRepository.Count(
                            item =>
                                item.OrderStatus > OrderStatus.ToPay && item.OrderStatus < OrderStatus.Succeed &&
                                item.AgencyId == user.AgencyId);
                    ViewBag.Completes = _orderRepository.Count(item => item.OrderStatus == OrderStatus.Succeed && item.AgencyId == user.AgencyId);
                    ViewBag.Turnover =
                        _orderRepository.FindList<Order>(item => item.OrderStatus == OrderStatus.Succeed && item.AgencyId == user.AgencyId).ToList()
                            .Sum(item => item.Fact);

                    var complaints = _orderRepository.Count(item => item.ComplaintType > ComplaintType.None && item.AgencyId == user.AgencyId);
                    var orders = _orderRepository.Count(item => item.AgencyId == user.AgencyId);
                    ViewBag.Complaints = $"投诉率：{((float)complaints/orders).ToString("p")}, 接到投诉：{complaints} 单";
                    return View("AgencySummary");
                case UserType.Withdrawals:
                    return RedirectToAction("Index", "PromoterInfo");
            }

            return View();
        }


        public ActionResult MonthSummary()
        {
            return PartialView("_MonthSummary", SummaryViewModel.Get(DateTime.Now.Year, DateTime.Now.Month));
        }
    }
}

AiJiaXi.Web/Areas/Admin/Controllers/SummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using Project.Domain.Entities;
using Project.Domain.Enums;
using Project.Domain.ViewModels.Admin;
using Project.Web.Filters;
using Microsoft.AspNet.Identity;

namespace Project.Web.Areas.Admin.Controllers
{
    [AdminAuthorize]
    public class SummaryController : Controller
    {
        private ApplicationUserManager _userManager;

        public SummaryController(ApplicationUserManager userManager)
        {
            _userManager = userManager;
        }

        // GET: Admin/Summary
        public ActionResult Turnnover(string year, string month)
        {
            int year_int = DateTime.Now.Year;
            int month_int = DateTime.Now.Month;

            if ((!string.IsNullOrWhiteSpace(year)) && year.IsInt())
            {
                year_int = int.Parse(year);
            }

            if ((!string.IsNullOrWhiteSpace(month)) && month.IsInt())
            {
                month_int = int.Parse(month);
            }

            var userId = User.Identity.GetUserId();
            var user = this._userManager.FindById(userId);

            Agency agency = null;

            if (user.UserType == UserType.Agency)
            {
                agency = user.Agency;
            }

            ViewBag.Date = $"{year_int}年{month_int}月";
            var model = SummaryViewModel.Get(year_int, month_int, agency);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_TurnoverPartial", model);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult TurnnoverSearchPost(string year, string month)
        {
            int year_int = DateTime.Now.Year;
            int month_int = DateTime.Now.Month;

            if ((!string.IsNullOrWhiteSpace(year)) && year.IsInt())
            {
                year_int = int.Parse(year);
            }

            if ((!string.IsNullOrWhiteSpace(month)) && month.IsInt())
            {
                month_int = int.Parse(month);
            }
            
            ViewBag.Date = $"{year_int}年{month_int}月";
            var model = SummaryViewModel.Get(year_int, month_int);
            return PartialView("_TurnoverPartial", model);
        }
    }
}

AiJiaXi.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AiJiaXi.Web/Areas/Admin/Views/Home/AgencySummary.cshtml
@model dynamic

@{
    ViewBag.Title = "白洗么";
    ViewBag.Top = "首页";
    ViewBag.Second = "代理商首页";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">白洗么后台管理系统</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-comments fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">26</div>
                            <div>当月营业额</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Turnnover", "Summary")">
                    <div class="panel-footer">
                        <span class="pull-left">查看当月统计</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-shopping-cart fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.Turnover</div>
                            <div>总营业额</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Turnnover", "Summary")">
                    <div class="panel-footer">
                        <span class="pull-left">查看相关统计</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-tasks fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.Going</div>
                            <div>进行中的订单</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Going", "Orders")">
                    <div class="panel-footer">
                        <span class="pull-left">查看所有进行中的订单</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-support fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.Completes</div>
                            <div>已完成订单投诉率</div>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <div class="panel-footer">
                        <span class="pull-left">&nbsp;</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <!-- /.row -->
</div>

AiJiaXi.Web/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "首页";
}

<h2>Index</h2>

AiJiaXi.Web/Areas/Admin/Views/Home/Summary.cshtml
@model dynamic

@{
    ViewBag.Title = "白洗么";
    ViewBag.Top = "首页";
    ViewBag.Second = "管理员";
}


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">白洗么后台管理系统</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-comments fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.Joins</div>
                            <div>加盟申请</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "JoinApplications")">
                    <div class="panel-footer">
                        <span class="pull-left">查看所有加盟申请</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-tasks fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.Users</div>
                            <div>用户信息</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "Users")">
                    <div class="panel-footer">
                        <span class="pull-left">查看所有用户</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-shopping-cart fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.Completes</div>
                            <div>近一个月完成的订单</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Going", "Orders")">
                    <div class="panel-footer">
                        <span class="pull-left">查看订单统计</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-support fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">￥@ViewBag.Turnover</div>
                            <div>近一个月的营业额</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Turnnover", "Summary")">
                    <div class="panel-footer">
                        <span class="pull-left">查看统计</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    @{ Html.RenderAction("MonthSummary", "Home"); }
</div>

@section Scripts{
}

AiJiaXi.Web/Areas/Admin/Views/Home/Withdrawals.cshtml
@model dynamic

@{
    ViewBag.Title = "白洗么";
    ViewBag.Top = "首页";
    ViewBag.Second = "推广员首页";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">白洗么后台管理系统</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-comments fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">26</div>
                            <div>已推广用户数</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "JoinApplications")">
                    <div class="panel-footer">
                        <span class="pull-left">查看当月统计</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-shopping-cart fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">124</div>
                            <div>总提成金额</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Going", "Orders")">
                    <div class="panel-footer">
                        <span class="pull-left">查看相关统计</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-tasks fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">12</div>
                            <div>总提现金额</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Going", "Orders")">
                    <div class="panel-footer">
                        <span class="pull-left">查看所有进行中的订单</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-support fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">13</div>
                            <div>已消费金额</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "Events")">
                    <div class="panel-footer">
                        <span class="pull-left">查看已完成订单</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <!-- /.row -->
</div>